#!/bin/bash

# only proceed script when started not by pull request (PR)
if [ $TRAVIS_PULL_REQUEST == "true" ]; then
  echo "this is PR, exiting"
  exit 0
fi

# enable error reporting to the console
set -e

# cleanup "_site"
rm -rf _site
mkdir _site

# clone remote repo to "_site"
git clone https://${GH_TOKEN}@github.com/ayastreb/jekyll-maps.git --branch gh-pages _site

gem install bundler:1.16.1

# build with Jekyll into "_site"
bundle exec jekyll build

# push
cd _site
git config user.email "anatoliy.yastreb@gmail.com"
git config user.name "Anatoliy Yastreb"
git add --all
git commit -a -m "Travis #$TRAVIS_BUILD_NUMBER"
git push origin gh-pages
